import { Product } from "@/types/database";

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "d0000000-0000-0000-0000-000000000001",
    link: "exide-inva-tubular-it500-150ah",
    image_url: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=800&q=80",
    status: "active",
    brand_series: "Inva Tubular Heavy Duty",
    brand_name: "Exide",
    model_sku: "EX-IT500-150AH",
    capacity: "150 Ah",
    voltage: "12V",
    plate_technology: "Tall Tubular Technology",
    total_warranty_months: 60,
    foc_months: 36,
    pro_rata_months: 24,
    approx_mrp: 18500,
    is_in_stock: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    detailed_layout: {
      dimensions_mm: { length: 505, width: 190, height: 410 },
      filled_weight_kg: 53.5,
      electrolyte_volume_litres: 18.2,
      terminal_type: "Standard Lead Post",
      recommended_inverter_va: "900VA - 1500VA",
      features: [
        "Thick tubular spine cast at high pressure (100 bar) for long life",
        "Factory-charged & ready for immediate installation",
        "Tower type design with low water loss technology",
        "Ceramic vent plugs with float guide indicators",
      ],
    },
  },
  {
    id: "d0000000-0000-0000-0000-000000000002",
    link: "luminous-eco-volt-neo-1050-sine-wave",
    image_url: "https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?auto=format&fit=crop&w=800&q=80",
    status: "active",
    brand_series: "Eco Volt Neo Series",
    brand_name: "Luminous",
    model_sku: "LUM-EV-NEO-1050",
    capacity: "900 VA / 756W",
    voltage: "12V DC / 230V AC",
    plate_technology: "Pure Sine Wave Microcontroller",
    total_warranty_months: 24,
    foc_months: 24,
    pro_rata_months: 0,
    approx_mrp: 7200,
    is_in_stock: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    detailed_layout: {
      dimensions_mm: { length: 275, width: 260, height: 115 },
      weight_kg: 8.5,
      display_type: "LED Indicators",
      max_charging_current_amp: 17,
      supported_battery_types: ["Flat Plate", "Tubular", "SMF/VRLA"],
      features: [
        "Pure Sine Wave output protects sensitive appliances",
        "Adaptive Fast Charging Technology extends battery life",
        "Supports wide battery capacity range (80Ah - 220Ah)",
      ],
    },
  },
  {
    id: "d0000000-0000-0000-0000-000000000003",
    link: "apc-back-ups-bx600c-in",
    image_url: "https://images.unsplash.com/photo-1558611848-73f7eb4001a1?auto=format&fit=crop&w=800&q=80",
    status: "active",
    brand_series: "Back-UPS Compact",
    brand_name: "APC by Schneider Electric",
    model_sku: "APC-BX600C-IN",
    capacity: "600 VA / 360W",
    voltage: "230V AC",
    plate_technology: "Sealed Maintenance Free (SMF)",
    total_warranty_months: 24,
    foc_months: 24,
    pro_rata_months: 0,
    approx_mrp: 3850,
    is_in_stock: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    detailed_layout: {
      battery_type: "12V 7.2Ah SMF Lead Acid",
      recharge_time_hours: 6,
      output_receptacles: 3,
      backup_time_desktop_pc_mins: 20,
    },
  },
];
